kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build -t ${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} -f docker/Dockerfile .
  volumes:
  - name: docker
    path: /var/run/docker.sock